trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
 - group: dockerhub
 - group: ssh
 - name: version
   value: $(git rev-parse --short HEAD)

steps:
  - task: InstallSSHKey@0
    inputs:
      knownHostsEntry: $(knownHosts)
      sshPublicKey: $(publicKey)
      sshKeySecureFile: 'id_rsa'
  - script: |
      java --version
    displayName: 'Checking Java Version'
  - script: |
      ./gradlew clean compileTest
    displayName: 'Compile files'
  - script: |
      ./gradlew test -x compileTest
    displayName: 'Run tests'
  - script: |
      ./gradlew build -x test
    displayName: 'Create jar'
  - script: |  
      docker build --tag lecsobkw/simplejavaapp .
      docker images
    displayName: 'Build docker image'
  - script: |
    echo 'Running integration tests on container'
    displayName: 'Running tests on container'
  - script: |
      chmod 777 ./tag.sh
      ls -l
      ./tag.sh $(version)
    displayName: 'Tag git branch'
  - script: |
      docker login -u $(username) -p $(password)
      docker tag lecsobkw/simplejavaapp lecsobkw/simplejavaapp:$(version)
      docker push lecsobkw/simplejavaapp:$(version)
    displayName: 'Push docker image'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
