trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      java --version
    displayName: 'Checking Java Version'
  - script: |
      ./gradlew clean compileTest
    displayName: 'Compile files'
  - script: |
      ./gradlew test -x compileTest
    displayName: 'Run tests'
  - script: |
      ./gradlew build -x test
    displayName: 'Create jar'
  - script: |  
      docker build --tag simple-java-app:1.0 .
      docker images
    displayName: 'Build docker image'
  
    
